// Generated by ReScript, PLEASE EDIT WITH CARE


function main() {
  var container = document.getElementById("app");
  if (container == null) {
    console.error("Error: Element with id 'app' not found");
  } else {
    container.innerHTML = "<div class=\"container mx-auto p-4\">\n        <h1 class=\"text-3xl font-bold text-blue-600\">Hello, World!</h1>\n      </div>";
  }
}

function handleDOMContentLoaded(_event) {
  main();
}

document.addEventListener("DOMContentLoaded", handleDOMContentLoaded);

export {
  main ,
  handleDOMContentLoaded ,
}
/*  Not a pure module */
